spring:
  application:
    name: scn-cloud-netflix-service
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

server:
  servlet:
    context-path: /
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka
    healthcheck:
      enabled: true

logging:
  file: log4j2.xml