spring:
  application:
    name: scn-cloud-netflix-eureka
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

server:
  servlet:
    context-path: /
  port: 8765

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

logging:
  file: log4j2.xml