spring:
  application:
    name: scn-cloud-alibaba-service

dubbo:
  application:
    name: scn-cloud-alibaba-dubbo-service
    qosEnable: false
  scan:
    basePackages: org.hinsteny.sca.service
  registry:
    id: hinsteny-zk-registry
    address: nacos://127.0.0.1:8848/nacos
  protocol:
    name: dubbo
    port: 12345

nacos:
  config:
    server-addr: 127.0.0.1:8848
    file-extension: yaml

logging:
  file: log4j2.xml